# symlink this to ~/.config/environment.d/90-nvidia.conf

# mostly Google Chrome stuff to make NVIDIA work
__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json
__NV_PRIME_RENDER_OFFLOAD=1
__GLX_VENDOR_LIBRARY_NAME=nvidia
__VK_LAYER_NV_optimus=NVIDIA_only

# mostly Firefox stuff to make NVIDIA work
LIBVA_DRIVER_NAME=nvidia
NVD_BACKEND=direct
MOZ_DISABLE_RDD_SANDBOX=1

#
# we also need
#
# sudo dnf install libva-nvidia-driver libva-utils
#
# and in firefox's about:config, set these to true:
#
# gfx.x11-egl.force-enabled
# media.hardware-video-decoding.force-enabled
# media.hardware-video-encoding.force-enabled
# media.ffmpeg.vaapi.enabled
# widget.dmabuf.force-enabled
#
