#
# Symlink this to ~/.config/environment.d/gnome-env.conf
#
# Then apply the changes with
#
# systemctl --user import-environment VARIABLE_IN_THIS_FILE
#
# or logout/login from Gnome.
#

GDK_GL=gles
